all:
	cd matMul; make all
	cd matSum; make all
	cd Subseqmax; make all
	cd dotProd; make all
	cd sorting; make all
	cd Subseqmax; make all

tests:
	cd matMul; make tests
	cd matSum; make tests
	cd Subseqmax; make tests
	cd dotProd; make tests
	cd sorting; make tests
	cd Subseqmax; make tests

clean:
	cd matMul; make clean
	cd matSum; make clean
	cd Subseqmax; make clean
	cd dotProd; make clean
	cd sorting; make clean
	cd Subseqmax; make clean
