all:
	cd bitonic; make all
	cd quicksort; make all
	cd matSum; make all
	cd subSeqMax; make all
	cd dotProd; make all
	cd matMul; make all
	cd vectorAdd; make all
	cd transFloat; make all
	cd transDouble; make all
	cd transComplexFloat; make all
	cd transComplexDouble; make clean

tests:
	cd bitonic; make tests
	cd quicksort; make tests
#	cd matSum; make tests
#	cd subSeqMax; make tests
#	cd dotProd; make tests
#	cd vectorAdd; make tests
	cd matMul; make tests

metrics: 
	cd bitonic; make metrics
	cd quicksort; make metrics
	cd matSum; make metrics
	cd dotProd; make metrics
	cd subSeqMax; make metrics
	cd matMul; make metrics
	cd vectorAdd; make metrics

events: 
	cd bitonic; make events
	cd quicksort; make events
	cd matSum; make events
	cd dotProd; make events
	cd subseqmax; make events
	cd matMul; make events
	cd vectorAdd; make events   
	
traces: 
	cd matSum; make traces
	cd dotProd; make traces
	cd subSeqMax; make traces
	cd matMul; make traces
	cd vectorAdd; make traces

	
clean:
	cd bitonic; make clean
	cd quicksort; make clean
	cd matSum; make clean
	cd subSeqMax; make clean
	cd dotProd; make clean
	cd matMul; make clean
	cd vectorAdd; make clean
	cd transFloat; make clean
	cd transDouble; make clean
	cd transComplexFloat; make clean
	cd transComplexDouble; make clean

