all:
	cd bitonic; make all
	cd dotProd; make all
	cd matSum; make all
	cd quicksort; make all
	cd Subseqmax; make all
	cd Subseqmax; make all
	cd matMul; make all

tests:
	cd bitonic; make tests
	cd quicksort; make tests
	cd matSum; make tests
	cd Subseqmax; make tests
	cd dotProd; make tests
	cd Subseqmax; make tests
	cd matMul; make tests
	
traces: 
	cd bitonic; make traces
	cd quicksort; make traces
	cd matSum; make traces
	cd Subseqmax; make traces
	cd dotProd; make traces
	cd Subseqmax; make traces
	cd matMul; make traces
	cd transFloat; make traces
	cd transDouble; make traces
	cd transComplexFloat; make traces
	cd transComplexDouble; make traces

metrics: 
	cd bitonic; make metrics
	cd quicksort; make metrics
	cd matSum; make metrics
	cd Subseqmax; make metrics
	cd dotProd; make metrics
	cd Subseqmax; make metrics
	cd matMul; make metrics

events: 
	cd bitonic; make events
	cd quicksort; make events
	cd matSum; make events
	cd Subseqmax; make events
	cd dotProd; make events
	cd Subseqmax; make events
	cd matMul; make events
	
clean:
	cd bitonic; make clean
	cd quicksort; make clean
	cd matSum; make clean
	cd Subseqmax; make clean
	cd dotProd; make clean
	cd Subseqmax; make clean
	cd matMul; make clean
