CC=nvcc
# -Xptxas -dlcm=cg
CFLAGS=-lm -O3 -arch sm_35 -w -ccbin g++-4.8 -Xptxas -dlcm=ca
NVPROF=nvprof
DEVICE_ID=0

METRICS=achieved_occupancy,gld_transactions,gld_transactions_per_request,gld_efficiency,gld_throughput,gld_requested_throughput,gst_transactions,gst_transactions_per_request,gst_efficiency,gst_throughput,gst_requested_throughput

